vim.pack.add({
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/ThePrimeagen/harpoon",
})
local harpoon = require("harpoon")
harpoon.setup()

vim.keymap.set("n", "<leader>A", function()
	harpoon:list():prepend()
	vim.cmd(":do User")
end)
vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
	vim.cmd(":do User")
end)
vim.keymap.set("n", "<leader>tt", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<leader>h", function()
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>j", function()
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>k", function()
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>l", function()
	harpoon:list():select(4)
end)

vim.keymap.set("n", "<leader>H", function()
	vim.cmd("vsplit")
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>J", function()
	vim.cmd("vsplit")
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>K", function()
	vim.cmd("vsplit")
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>L", function()
	vim.cmd("vsplit")
	harpoon:list():select(4)
end)