return {
	"ThePrimeagen/harpoon",
	branch = "harpoon2",
	dependencies = { "nvim-lua/plenary.nvim" },
	config = function()
		local harpoon = require("harpoon")
		local harpoon_extensions = require("harpoon.extensions")
		harpoon.setup()
		harpoon:extend(harpoon_extensions.builtins.highlight_current_file())
		harpoon:extend(harpoon_extensions.builtins.navigate_with_number())

		vim.keymap.set("n", "<leader>A", function()
			harpoon:list():prepend()
		end)
		vim.keymap.set("n", "<leader>a", function()
			harpoon:list():add()
		end)
		vim.keymap.set("n", "<leader>tt", function()
			harpoon.ui:toggle_quick_menu(harpoon:list())
		end)

		vim.keymap.set("n", "<leader>h", function()
			harpoon:list():select(1)
		end)
		vim.keymap.set("n", "<leader>j", function()
			harpoon:list():select(2)
		end)
		vim.keymap.set("n", "<leader>k", function()
			harpoon:list():select(3)
		end)
		vim.keymap.set("n", "<leader>l", function()
			harpoon:list():select(4)
		end)
		vim.keymap.set("n", "<leader>H", function()
			vim.cmd("vsplit")
			harpoon:list():select(1)
		end)
		vim.keymap.set("n", "<leader>J", function()
			vim.cmd("vsplit")
			harpoon:list():select(2)
		end)
		vim.keymap.set("n", "<leader>K", function()
			vim.cmd("vsplit")
			harpoon:list():select(3)
		end)
		vim.keymap.set("n", "<leader>L", function()
			vim.cmd("vsplit")
			harpoon:list():select(4)
		end)
	end,
}
