return {
  "nvim-treesitter/nvim-treesitter",
   ensure_installed = {
      "bash",
      "css",
      "go",
      "graphql",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "lua",
      "markdown",
      "regex",
      "rust",
      "scss",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "yaml",
      "zig",
    },
    highlight = {
      enable = true
    },
    indent = {
      enable = true,
    },
}
